spring.application.name=learn-spring-security-jwt

spring.data.mongodb.uri=mongodb://admin:password@localhost:27017/test?authSource=admin
jwt.secret=MySuperSecretKeyForJwtAuthenticationSpringBoot2026MySuperSecretKey
jwt.expiration=86400000
spring.data.mongodb.auto-index-creation=true