spring.application.name=learn-spring-security-jwt

spring.data.mongodb.uri=${mongodb://admin:password@localhost:27017/test?authSource=admin}
jwt.secret=${MySuperSecretKeyForJwtAuthenticationSpringBoot2026MySuperSecretKey}
jwt.expiration=86400000
spring.data.mongodb.auto-index-creation=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${bossdkthe51@gmail.com}
spring.mail.password=${nhvl zskm ksix uxnq}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true